[package]

name = "example"
version = "0.0.0"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
build = "build.rs"

[dependencies]
rand = "*"
rustc-serialize = "*"
rustful = "0.9"

[dependencies.symbiosis_static]
path = "../static"

[build-dependencies.symbiosis]
path = ".."
