language: rust
os:
  - linux
  - osx
script:
  - cargo test
  - cd pattern
  - cargo test
  - cargo doc
  - mkdir ../tokenizer/target
  - mv target/doc/ ../tokenizer/target/doc
  - cd ../tokenizer
  - cargo test
  - cargo doc
  - mkdir ../dynamic/target
  - mv target/doc/ ../dynamic/target/doc
  - cd ../dynamic
  - cargo test
  - cargo doc
  - mkdir ../static/target
  - mv target/doc/ ../static/target/doc
  - cd ../static
  - cargo test
  - cargo doc
  - mv target/doc/ ../target/doc
  - cd ../example
  - cargo build
  - cd ..
  - cargo doc
after_success:
  - sh scripts/upload_doc.sh
