language: rust
os:
  - linux
  - osx
branches:
  only:
    - master
    - auto
script:
  - mkdir target
  - cd render_tests
  - bash run.sh
  - cd ../pattern
  - cargo doc
  - mkdir ../tokenizer/target
  - mv target/doc/ ../tokenizer/target/doc
  - cd ../tokenizer
  - cargo test
  - cargo doc
  - mkdir ../dynamic/target
  - mv target/doc/ ../dynamic/target/doc
  - cd ../dynamic
  - cargo doc
  - mkdir ../static/target
  - mv target/doc/ ../static/target/doc
  - cd ../static
  - cargo doc
  - mv target/doc/ ../target/doc
  - cd ../example
  - cargo build
  - cd ..
  - cargo doc
after_success:
  - sh scripts/upload_doc.sh
