language: rust
os:
  - linux
  - osx
script:
  - cargo test
  - cargo doc
  - cd pattern
  - cargo test
  - cargo doc
  - rsync -avq target/doc/* ../target/doc
  - cd ../tokenizer
  - cargo test
  - cargo doc
  - rsync -avq target/doc/* ../target/doc
  - cd ../dynamic
  - cargo test
  - cargo doc
  - rsync -avq target/doc/* ../target/doc
  - cd ../rust
  - cargo test
  - cargo doc
  - rsync -avq target/doc/* ../target/doc
  - cd ../example
  - cargo build
  - cd ..
after_success: curl https://raw.githubusercontent.com/ogeon/travis-doc-upload/master/travis-doc-upload.sh | sh
