language: rust
os:
  - linux
  - osx
script:
  - cargo test
  - cd pattern
  - cargo test
  - cargo doc
  - mkdir ../tokenizer/target
  - mv target/doc/ ../tokenizer/target/doc
  - cd ../tokenizer
  - cargo test
  - cargo doc
  - mkdir ../dynamic/target
  - mv target/doc/ ../dynamic/target/doc
  - cd ../dynamic
  - cargo test
  - cargo doc
  - mkdir ../rust/target
  - mv target/doc/ ../rust/target/doc
  - cd ../rust
  - cargo test
  - cargo doc
  - mv target/doc/ ../target/doc
  - cd ../example
  - cargo build
  - cd ..
  - cargo doc
after_success: curl https://raw.githubusercontent.com/ogeon/travis-doc-upload/master/travis-doc-upload.sh | sh
