[package]
name = "symbiosis_core"
version = "0.0.1"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]

build = "build.rs"

[lib]
name = "symbiosis_core"

[dependencies]
html5ever = "0.5"
string_cache = "0.2"
tendril = "0.2"
lalrpop-util = "0.10"

[build-dependencies.lalrpop]
varsion = "0.10"
