[package]
name = "symbiosis_tokenizer"
version = "0.0.1"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]

[lib]
name = "symbiosis_tokenizer"

[dependencies]
html5ever = "0.5"
string_cache = "0.2"

[dependencies.symbiosis_core]
path = "../core"
